<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaf8e9a33721e22c3aa6d0d6542c674df
{
    public static $prefixLengthsPsr4 = array (
        'e' => 
        array (
            'enshrined\\svgSanitize\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'enshrined\\svgSanitize\\' => 
        array (
            0 => __DIR__ . '/..' . '/enshrined/svg-sanitize/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaf8e9a33721e22c3aa6d0d6542c674df::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaf8e9a33721e22c3aa6d0d6542c674df::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
